### ISSUE TITLE
Workstation gem customizations still setup .chefdk dir

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#823] opened 2019-12-20 19:14 UTC
Our customizations for rubygems to install gems to the user's home dir are still pointing to .chefdk

See https://github.com/chef/chef-workstation/blob/master/omnibus/files/rubygems-customization/default/operating_system.rb

Related: #824

**Comment by tyler-ball** [comment] 2020-02-19 18:37
Closing this as a duplicate of https://github.com/chef/chef-workstation/issues/689

**Closed by tyler-ball** 2020-02-19 18:37 UTC
Labels: Aspect: Packaging, Aspect: Portability, Aspect: Stability, Triage: Feature Request, Type: Chore
