### ISSUE TITLE
Failing to execute CHEF scripts via workstation to client nodes on Windows’ platform 

### ISSUE THREAD

**Issue by JMLayn** [chef/chef-workstation#373] opened 2019-05-21 21:12 UTC
SQL_2017_ONLY_PROVISION_STD_x64

[✔] Packaging cookbook... done!

[✔] Generating local policyfile... exporting... done!

[✖] Applying SQL_2017_ONLY_PROVISION_STD_x64::default from C:/Users/<user name>/chef-repo/cookbooks/SQL_2017_ONLY_PROVISION_STD_x64 to target.

|__ [✖] [<server name>.<domain name>.net] Failed to converge SQL_2017_ONLY_PROVISION_STD_x64::default.

Could not determine reason for converge failure
 
STDOUT (may be blank)
 
STDERR (may be blank)

 

  Cannot find path 'C:\Users\<user name>\AppData\Roaming\chef-workstation\cache\run-report.json' because it does not exist.

At line:1 char:1

+ type $env:APPDATA/chef-workstation/cache/run-report.json

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (C:\Users\<user name>...run-report.json:String) [Get-Content], ItemNotFoundException

    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

 

 

An error occurred while converging the remote host.

I was unable to retrieve the log file which would allow

me to provide more information.  Above is the output

that occurred while trying to retrieve the remote log file.

PS C:\Users\<user name>\chef-repo\cookbooks>

## Chef Workstation Version
unknown

## Platform Version
windows

**Comment by jonsmorrow** [comment] 2019-06-10 20:14
Hi there lets see if we can figure out what is going on. From your output above its hard for me to see what you are trying accomplish. I assume this is a `chef-run` but can't see much more beyond that. Do you have a copy of the cookbook you are trying to run and the full command you executed?

**Comment by JMLayn** [comment] 2019-06-10 21:01
Hi Jon,
You and I along with Ricardo Lupo had talked about this at ChefConf. I did find out just a few days ago that the person is running is the supermarket MSSQL cookbook.

https://supermarket.chef.io/cookbooks/sql_server

From what it say in the cookbook readme is that winrm execution is not possible so I figured that would include using chef-run as well. So this maybe that cause of the error and unrelated to Chef Workstation.

Thanks,

Jason

**Comment by mfoster86** [comment] 2019-06-11 19:33
Bump on this thread. I am running into this same issue, reverting Chef-Client to version 14.13.11 then cookbooks converge successfully on target node. Is there a way to specify which chef-client version to install on a target system via chef-run?

- Chef Workstation, chef-run version = 0.2.8
- Node = Windows Server 2016


Cannot find path 'C:\Users<user name>\AppData\Roaming\chef-workstation\cache\run-report.json' because it does not exist.

The **stack-trace.log** shows the following:
Backtrace:
ChefApply::Errors::CCRFailureMapper::RemoteChefRunFailedToResolveError: ChefApply::Errors::CCRFailureMapper::RemoteChefRunFailedToResolveError
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/errors/ccr_failure_mapper.rb:31:in `raise_mapped_exception!'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/action/converge_target.rb:166:in `handle_ccr_error'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/action/converge_target.rb:54:in `perform_action'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/action/base.rb:116:in `block in run'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/telemeter.rb:85:in `block in timed_capture'
	/opt/chef-workstation/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/telemeter.rb:85:in `timed_capture'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/telemeter.rb:70:in `timed_action_capture'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/action/base.rb:114:in `run'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:252:in `converge'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/cli.rb:154:in `block (2 levels) in render_converge'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/ui/terminal/job.rb:31:in `run'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-apply-0.2.8/lib/chef_apply/ui/terminal.rb:60:in `block (2 levels) in render_parallel_jobs'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/tty-spinner-0.9.0/lib/tty/spinner.rb:225:in `execute_job'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/tty-spinner-0.9.0/lib/tty/spinner/multi.rb:150:in `block (2 levels) in auto_spin'
	/opt/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

**Comment by mfoster86** [comment] 2019-06-11 20:13
My issue has been resolved. I realized after posting this I should have checked my Chef Workstation version, v2.5-something. Upgraded to latest version: 0.4.1 and that resolved the issue.

**Comment by tyler-ball** [comment] 2019-06-17 20:25
@JMLayn `chef-run` does use winrm connections so it is possible that prevents the remote converge from installing SQL server. Upgrading to the latest version of Chef Workstation fixed the issue for @mfoster86 - could you try that and see if you still get the same issue?

If that does not help, we can try to setup a repro. The `Cannot find path 'C:\Users\AppData\Roaming\chef-workstation\cache\run-report.json' because it does not exist.` is actually a second error occuring when we try to scrape the failed converge info from the remote box. We can make that experience better so it does not obscure the actual error that is happening trying to perform the converge.

**Comment by drodriguez** [comment] 2019-06-26 00:14
Sorry I lost some of the details while trying to get this fixed, but I hope the clues in this comment led to fixing this.

I downloaded 15.0.300 of Chef Infra Client (I only tested the stable, not the current builds, sorry). From the release notes it includes Ruby 2.6.3, while the latest Chef Infra Client 14.x seems to use 2.5.5.

The problem happens in the file https://github.com/ruby/ruby/blob/v2_6_3/ext/win32/lib/Win32API.rb that was modified in 2.6 from the version in 2.5: https://github.com/ruby/ruby/commit/3be45505586ece2882529ab383351febca7f5683

That change mixed with the gem structured_warnings 0.3.0 seems to be the cause of my problems converging any cookbook (probably because most of the `depends 'windows'`). Seems that the author is aware of the problem and has WIP solution, but it haven't been published yet: https://github.com/schmidt/structured_warnings/pull/11

Seems that using the latest available Chef Infra Client from the 14.x version works for me.

**Comment by tyler-ball** [comment] 2019-09-30 20:10
@drodriguez Thanks for looking that up! We reached out to the maintainer of that gem and they released a new version that is included in the latest Chef Workstation release (0.9.42). I'm going to close this issue but please comment here if you are still experiencing an issue!

**Closed by tyler-ball** 2019-09-30 20:10 UTC
Labels: Platform: Windows, Priority: Medium, Triage: Needs Information
