### ISSUE TITLE
chef install/update generates inconsistent policy hashes because of caching

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef-workstation#1273] opened 2020-06-19 06:32 UTC
## Description

When running chef install/update from two separate system it's possible for it to generate completely different policy object hashes even when all dependent cookbook versions are the same if the local cache was populated using berks.
## Platform Version

**To Reproduce**
Here is a scenario where this can happen:

### On workstation A
User creates a cookbook that depends on logrotate 2.2.0, they then use berks install to cache the dependency locally, and then upload it to the chef-server using `berks upload`.

On the Supermarket logrotate includes a `metadata.rb` file.  When the cookbook uploaded to the chef-server that file gets stripped out and converted to a `metadata.json` file.  

Then they create a Policy file for that cookbook and set the default_source to the chef-server.  Run the `chef install` command and get a Policyfile.lock.json with a hash generated.

Since berks has already cached the cookbook into `~/.chefdk/cache/cookbooks/logrotate-2.2.0` the chef command doesn't download it from the chef-server like the Policyfile says it should for the default_source.

### On workstation B
On a new machine they pull down the cookbook or Policyfile and run `chef install/update` which will cache the logrotate cookbook from the chef-server and generate a new Policyfile.lock.json with a different object hash.

### On workstation A
If we then clear out the cache on the first workstation `rm -rf ~/.chefdk/cache/cookbooks/*` and then run `chef update`, it will download the cookbooks from the chef-server and update the Policyfile.lock.json with the same hash from Workstation B.

**Expected behavior**
Running chef install/update on different machines with no changes to dependencies should generate the same hash.

**Comment by tyler-ball** [comment] 2020-07-29 17:38
Moving this to the Workstation team board to work on

**Comment by marcparadise** [comment] 2020-08-14 15:49
I have not been able to reproduce this so far.  I did not use two different machines, but the steps below should show that was OK for this case.  My results differed  along the way. 

Berksfile: 

```
cookbook "logrotate", "=2.2.0"
source 'https://supermarket.chef.io'
```
Policyfile: 
```
name 'test1' 
default_source :chef_server, "https://api.chef.io/organizations/MYORG"
cookbook 'logrotate', '= 2.2.0'
run_list 'test1::default'
```
1. I ran `berks install` which downloaded logrotate 2.2.0. 
  a. It cached to `~/.berkshelf/cookbooks/logrotate-2.2.0`.  Nothing was placed in `~/.chefcli/cache, ~/.chef-workstation/cache, ~/.chefdk/cache`. 
  b. The cached logrotate included `metadata.rb` and `metadata.json` 
2. I ran `berks push` which uploaded logrotate 2.2.0 to the chef server
3. I ran `chef install` which pulled down logrotate 2.2.0 from the chef server into `~/.chef-workstation/cache/cookbooks/logrotate-2.2.0/`. 
  a.  It also had both `metadata.rb` and `metadata.json`. 
  b. generated hash/rev ended in `cab1b6d43`
4. I nuked all caches to be safe: `~/.chef-workstation/cache, ~/.berkshelf/cookbooks, ~/.chefdk, ~/.chefcli` 
5. I copied cb to a new location.  This probably wasn't necessary, but between clearing caches and this it should be the same as being on a new machine. 
6. In the new location, I did a `chef update`.  The hash/revision provided was the same as in 3b, above. 

The key differences that I'm seeing are: 
a) Most important: the cookbook cache by berkshelf is not cached in a location used by policy/chef install, so I do not see how the berkshelf-cached version could have an affect on the version installed by `chef install`, which retrieves it from the server.  The description said, "the chef command doesn't download it from the chef-server like the Policyfile says it should for the default_source.", but that doesn't seem to be what's happening - the `chef` command did download it from chef-server in this scenario. 

b) the logrotate-2.0 cookbook in the berkshelf cache already  had both a metadata.rb and a metadata.json, after `berks install` and before `upload`.  I verified that the original cookbook source did not have a metadata.rb; so either this is being provided by supermarket or in the `berks install` process.   To try to track this down, I used `knife supermarket install logrotate 2.2.0`; the installed logrotate cookbook also had both the `metadata.json` and `metadata.rb` files.

@dheerajd-msys is there anything in this test that's inconsistent with what you did?  Too, what version of Workstation (or DK) did you use to recreate the issue?

**Comment by marcparadise** [comment] 2020-08-14 15:52
I do wonder if there was _already_ a logrotate-2.0 cached somewhere accessible, and that did not contain the metadata.json? I will force this scenario and see how it goes.

**Comment by marcparadise** [comment] 2020-08-14 16:14
Okay, confirmed. When I removed only the metadata.json file from ` ~/.chef-workstation/cache/cookbooks/logrotate-2.0` and re-ran `chef update`, I did get a different checksum. 

This means if someone has an inconsistency in their local cache - either via direct modification, or perhaps they had downloaded an earlier iteration of a cookbook at the same version, and contents have since changed for that version - we do not invalidate the cache based on change content. The checksum changes, and we will upload the un-checked cached version of the cookbook when we `push`. 


Simplified reproduction scenario, from a cookbooks repository: 

```
mkdir cookbooks 
cd cookbooks
chef generate cookbook testa
chef generate cookbook testb
cd ..
knife cookbook upload testa 
cd cookbooks/testb
# change default_source in Policyfile.rb to chef server w/ url 
# add cookbook testa to Policyfile.rb
chef install
rm  ~/.chef-workstation/cache/cookbooks/testa-0.1.0/metadata.json
chef update
```

This will create a new hash. If you restore the metadata.json and run `update` again, it will restore the old hash, 


Initial install: 

```
√ cookbooks/testb $ chef install
-snip-         
Installing testb >= 0.0.0 from path
Installing testa 0.1.0

Lockfile written to /home/marc/testing/cookbooks/testb/Policyfile.lock.json
Policy revision id: 585d75d222ec6a131bee38d1c96419e6a68c937736f9c871c72b1336582c4388
```

Remove a file from cache: 

```
 rm  ~/.chef-workstation/cache/cookbooks/testa-0.1.0/metadata.json
√ cookbooks/testb $ chef update                                                     
Attributes already up to date
-snip- 
Installing testb >= 0.0.0 from path
Using      testa 0.1.0

Lockfile written to /home/marc/testing/cookbooks/testb/Policyfile.lock.json
Policy revision id: 7f4fff72fd82971819fa72783e52682e5f37f6ca83a42469b3d36a339f655fe7
```

Clear the cache to force a redownload: 
```
√ cookbooks/testb $ rm -rf ~/.chef-workstation/cache/cookbooks 
√ cookbooks/testb $ chef update                               
-snip- 
Caching Cookbooks...
Installing testb >= 0.0.0 from path
Installing testa 0.1.0

Lockfile written to /home/marc/testing/cookbooks/testb/Policyfile.lock.json
Policy revision id: 585d75d222ec6a131bee38d1c96419e6a68c937736f9c871c72b1336582c4388
```

**Comment by marcparadise** [comment] 2020-08-14 16:39
It seems that the right answer here will be to invalidate the cache if it changes, and redownload before updating the policy lockfile.   

Following that trail led here: https://github.com/chef/cookbook-omnifetch/blob/master/lib/cookbook-omnifetch/base.rb#L67

The only place we have that will re-download cookbook components is here, and it will not be invoked if the cookbook is present and passes cache validation. (In some cases, cache validation may not be run at all - chef server source seems to be one of them): https://github.com/chef/cookbook-omnifetch/blob/427993199332dace31f389cb22c2f46a288cc2ba/lib/cookbook-omnifetch/metadata_based_installer.rb#L55

The cookbook metadata here _should_ include the checksum, but CookbookOmnifetch does not validate it either at download time or when checking cache.

**Comment by marcparadise** [comment] 2020-08-18 15:59
Caching Fix Proposal

## Current State

`chef push` and `chef update` cache validation consists of checking if the `cookbook_name-version` directory exists in the cache directory. If so, it is assumed to be cached and valid. 

Otherwise  the cookbook (or artifact) is re-downloaded to a staging area.  The complete cookbook is then moved from staging into the cache as a single operation.

## Proposed Behavior 

`chef push` and `chef update` will verify each dependent cookbook by downloading its content manifest  and checking files present in cache against those listed in the content manifest. 
  - Any cookbook content that does not match the checksum from Chef Infra Server will be refreshed.

  - Any cookbook that does not have a `manifest.rb`/json` as part of its content will still be considered invalid 
  - Any cookbook that has missing files based on its content manifest will fail to `install`/`update`. (Same as today) 

* Cookbook content will be downloaded directly into cache.  If a download or write fails, any partial file will be removed and the operation will be considered failed. 
* Any cookbook content that does not exist in the manifest will be removed from cache.

## Impacts

In Workstation the cookbook cache location is shared between `chef` `capture`, `report`, `install`, `update`, and `push`.  `capture` and `report` already use the described 'new' caching mechanism.  This means someone running those tools together on the same Chef Workstation node may already be seeing the following impacts. 

### Stale Cache

If someone is updating cookbooks on chef server without updating the version, `chef install/update` will
not update locally cached cookbooks.  This means that a `chef push` will include the old content
for dependent cookbooks.

With this change to caching, `chef install/update` will now ensure that the cached cookbook of a given version is in sync with the same version on the Chef Infra Server. This may cause unexpected cookbook changes to be published/incorporated as artifacts into the policy. 

### Modified Cache

Any workflows or pipelines that rely on modifying internally cached content are currently safe in doing this -
as long as the cookbook-name.version directory exists in the cache, and as long as it has a valid `metadata.rb/json`,
it will not be modified when `chef install/update` is run.

With this change to caching, locally modified cache content will be overwritten on every `chef install/update`.  This has the potential to break pipelines that do inline cache modification instead of committing/pushing the updates to CIS.

### Performance 

Because cookbook manifests will always be fetched, this will be marginally slower since we'll now be making at least one request
per cookbook (more if any files are found invalid).

## Mitigations

It is possible to introduce the new caching behavior behind a feature flag, while deprecating the original behavior. This would let us introduce it gradually and only make it default after customers have time to adjust to the upcoming behavior; and finally we'd remove support for the original implementation.   Given that caching is an internal mechanism, I'm not sure that we need to take this step. 

## Implementation Notes 

The proposed caching mechanism is very similar to that used in the `chef-analyze` binary. I'm not sure yet if this is the right wya, but we have the option of offloading cache population to this binary instead of re-implementing it in `chef-cli`.   One limitation of this route   is that `chef-analyze` can populate cache from chef server cookbooks or artifacts, but it can't yet support populating cache from other sources (git, supermarket).

**Comment by tyler-ball** [comment] 2020-08-18 17:49
> Was the cache of 'installed' cookbooks intended to be locally user-modifiable, such that those modifications could be deployed via policyfile without invalidating cache?

I agree this does *not* seem to be the intent. A `berks install` or `chef install` is generating a lock of the cookbook and dependencies. Any changes to that cookbook or its dependencies should generate a new lock (theoretically). I would think that any changes to that cookbook, either from the source or in the cache, would still generate a new lock.

> Since berks has already cached the cookbook into ~/.chefdk/cache/cookbooks/logrotate-2.2.0 the chef command doesn't download it from the chef-server like the Policyfile says it should for the default_source.

Reading the original bug, it seems like this line is the key. Because the current cache checking only validates the directory name and changes _in_ that cached directory are ignored. So on a workstation if I:

1. `berks install` to grab a cookbook with a `metadata.rb` into my cache
1. `berks upload` to upload it to the Chef Server, converting `metadata.rb` to `metadata.json` *on the server*
1. Now my local cached copy of the cookbook is different than the version on the server (`metdata.rb` vs `metdata.json`)
1. `chef install` locally will create a different cookbook hash than doing `chef install` on a different machine that pulls the cookbook from the Chef Server.

If I am following along with everything so far I think your proposal to make cache validation actually check the contents makes sense. It would mean that last `chef install` would see that my local copy of the cookbook (`metadata.rb`) is incorrect compared to the version on the server (`metadata.json`) and would update my local cache.

## Stale Cache

I agree, this change to behavior would need to be communicated clearly. It seems to me a bug that users would be modifying cookbook content in a cache instead of modifying the source. I can't imagine why someone would do this, but it is certainly possible.

Because this is a bug fix I don't *think* we should feature flag it, just communicate clearly that we fixed a bug that may change behavior. Thoughts?

**Comment by tyler-ball** [comment] 2020-08-18 19:54
### Performance

Is this cache checking going to be performed on a `chef-client` run? Does Chef Infra do better cache validation than just checking the directory name?

**Comment by marcparadise** [comment] 2020-08-19 16:32
Answer to the original question seems to be that the caching mechanism wasn't intended to provide support for local modifications to internal cache - it's just the way it was built. 

We've also verified internally that we haven't been encouraging customers to modify contents in their cache directory locally. 

Given that, I'll proceed with the changes outlined above. After further discussion we won't be feature flagging this, because caching is an internal implementation; however we will call out the risks in the Workstation release notes that include this change.

**Comment by marcparadise** [comment] 2020-08-19 16:33
I did take a look at replacing the caching of chef-server based cookbooks with a call into the `chef-analyze` binary.  While this worked and performed very well, it is not compatible with our use of the `chef-cli` gem in habitat packages as part of Effortless. This is something we may revisit further down the road; but for the time being the cache changes will be implemented in the chef-cli/cookbook-omnifetch gems.

**Comment by marcparadise** [comment] 2020-08-26 14:07
I missed your earlier question tyler-ball: 



> Is this cache checking going to be performed on a chef-client run? Does Chef Infra do better cache validation than just checking the directory name?

No, chef client has its own implementation via `ChefFS`  and does not rely on this.

**Comment by marcparadise** [comment] 2020-08-26 14:32
> 

   >  berks install to grab a cookbook with a metadata.rb into my cache
   >  berks upload to upload it to the Chef Server, converting metadata.rb to metadata.json on the server

This is incorrect though - the `berks install` will install to the `berks` cache, which is entirely separate from the Workstation/DK cash that `chef install` uses. So when you berks upload, then `chef install`, the `chef` cache is populated with both metadata.rb/metadata.json. 

I couldn't reproduce this issue at all as originally described, and it looks like that is because `berks` and `chef` have different cache locations.If they're  configured to be the same, that would definitely cause the issue to surface as described.

**Closed** 2020-09-01 01:02 UTC
Labels: Aspect: Stability, Triage: Confirmed, Type: Bug

**Comment by karmix** [comment] 2022-02-08 20:24
Since nobody could reproduce the issue with berks, I understand that we reinterpreted the issue to be something like:

> When running chef install/update from two separate systems it's possible for it to generate completely different policy object hashes even when all dependent cookbook versions are the same if the __[upstream cookbook is modified after being cached locally]__.

Specifically, after caching a cookbook, `chef` would never update it, and would continue to generate policy hashes for a previous iteration of the cookbook until someone manually removed it from the cache.

The solution (chef/cookbook-omnifetch#33) solved the issue by forcing the re-synchronization of locally cached cookbooks with their upstream sources on a Chef Server.  This introduced a regression where other tools like `chefspec` and `test-kitchen` no longer work when they do not have access to the Chef Server (reported in chef/cookbook-omnifetch#35).

Though a Chef Server was used as a cookbook source in the steps for reproducing this issue, nothing in the description said the problem was specific to using cookbooks from a Chef Server.  It is still possible to reproduce the rephrased issue using artifact server and supermarket cookbook sources, so I do not believe we should consider this issue resolved.
