### ISSUE TITLE
kitchen does not find gems after upgrade from 0.3.2 to 0.4.x

### ISSUE THREAD

**Issue by mrmarbury** [chef/chef-workstation#393] opened 2019-06-27 09:38 UTC
## Description
When upgrading from chef-workstation version 0.3.2 to 0.4.1 or 0.4.2 kitchen complains about not finding its drivers anymore.

`kitchen list`
`Message: Could not load the 'openstack' driver from the load path`

I did a `chef gem install kitchen-openstack` again and the gem is located under `~/.chefdk/gem/ruby/2.6.0/gems/`

`> ls ~/.chefdk/gem/ruby/2.6.0/gems/`
`chef-vault-testfixtures-3.0.1 fog-core-2.1.0                fog-openstack-0.3.10          kitchen-openstack-3.6.2       net-ssh-4.2.0                 test-kitchen-1.25.0`

Did anything change here?

## Chef Workstation Version
Upgrade form 0.3.2 to 0.4.2

## Platform Version
macos 10.14.5

**Comment by tyler-ball** [comment] 2019-07-01 20:29
@mrmarbury I don't think we shipped `kitchen-openstack` in Chef Workstation 0.3.2. I did a fresh install of that and only found `fog-openstack`.

My guess is that you previously had `kitchen-openstack` installed using `chef gem install` and somehow deleted your `~/.chefdk` folder. This would cause it to go missing. Do you think thats possible?

**Comment by tyler-ball** [comment] 2019-07-01 20:31
After you did a `chef gem install kitchen-openstack` did your `kitchen list` succeed?

**Comment by tyler-ball** [comment] 2019-07-01 20:35
One other note - Chef Workstation 0.3.2 would have installed its gems to `~/.chefdk/gem/ruby/2.5.0/gems/` while Chef Workstation 0.4.2 installs its gems to `~/.chefdk/gem/ruby/2.6.0/gems/`. Do you have an existing `2.5.0` gems folder?

If so this is (unfortunately) the expected behavior. When we bump major Ruby versions it installs gems to that new path. Chef Workstation isn't smart enough to re-install gems when bumping major Ruby versions.

**Comment by mrmarbury** [comment] 2019-07-02 07:14
`kitchen-openstack` wasn't shipped with Chef Workstation. I installed it with a `chef gem install` and it worked with 0.3.2. After upgrading do 0.4.2 I did all sorts of things,  like:
- reinstalled all custom gems with `chef gem install` (they are available in `~/.chefdk/gem/ruby/2.6.0/gems/`)
- deleted `~/.chefdk` and reinstalled with `chef gem install`
- even forked `kitchen-openstack`, broadened the deps to support kitchen 2, built a gem and installed that. (there is pull request https://github.com/test-kitchen/kitchen-openstack/pull/195 by tsmith@chef.io. stating that this should work)

I currently try to figure out what the reasons are. The only other custom gem we use (`chef-vault-testfixtures`) works well only kitchen does not find the gem. I may try and put the gem to the chef-workstation install directory. Let me see

**Comment by mrmarbury** [comment] 2019-07-02 07:30
nope, doesn't work. Either kitchen is faulty or the kitchen-openstack gem is broken. Even though I suspect the latter I hope you can give me a better hint on what's going on anyway.

**Comment by tyler-ball** [comment] 2019-08-05 20:14
Another question, because I think I may know the issue. What does the response from `which kitchen` give you? If it points to `/opt/chef-workstation/bin/kitchen` you can try deleting that and seeing if `kitchen list` now finds the driver.

**Comment by ramereth** [comment] 2019-10-07 20:26
@mrmarbury we released kitchen-openstack-4.0.0 a few months back which adds support for Kitchen 2. Are you still seeing that problem with kitchen-openstack?

**Comment by afiune** [comment] 2019-11-13 18:34
From the above conversation, I think we might need to update both, Chef Workstation and the openstack gem to verify if this is still an issue.

**Comment by tas50** [comment] 2021-02-13 06:59
Everything is bumped at this point so I'm going to close this one out.

**Closed by tas50** 2021-02-13 06:59 UTC
Labels: Aspect: Packaging, Triage: Needs Information
