### ISSUE TITLE
Release Chef Workstation 0.11.x

### ISSUE THREAD

**Issue by afiune** [chef/chef-workstation#652] opened 2019-11-01 19:01 UTC
Expedite a release of Chef Workstation to solve a couple of regressions.

- [x] Ensure we get openssl / libxml2 packaged
- [x] ship chef go update
- [ ] write release notes
- [ ] ship it
- [ ] announce it
- [ ] push to hombrew/chocolatey

**Comment by tas50** [comment] 2019-11-04 17:16
Dupe of #667

**Closed by tas50** 2019-11-04 17:16 UTC
Labels: Aspect: Packaging, Status: Adopted, Triage: Confirmed
